# Generated by Django 4.2.2 on 2023-06-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230615_1016'),
        ('blog', '0004_rename_comment_comment_post'),
    ]

    operations = [
    ]
