# Generated by Django 4.2.2 on 2023-06-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20230626_0818'),
        ('blog', '0009_alter_comment_text'),
    ]

    operations = [
    ]
